#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Hello again! Today we will be learning about the "While" loop.
//The "While loop allow for things to be repeated over and over again until you tell it to stop. This makes it a powerful tool for driving
//where you need to constantly check for updates on the state of the controller.

task main()//First, we are going to add a while loop inside task main.
{
	while(true)//Again, you need the curly braces for the while loop. These tell it what code to repeat. We also see the term "true" inside the parentheses.
	{//The term "true" tells the processer to repeat this forever. Later, we will look at other things you can put inside the parentheses to make it do different things.
		//Inside your while loop, we are going to write vexRT[Ch3] = motor[leftDrive];
		vexRT[Ch3] = motor[leftDrive];
		//Below this, we will write the same thing, but for the opposite side of the drive. This is known as "Tank Drive".
		vexRT[Ch2] = motor[rightDrive];
		//Now the two sticks will each control each side of the drive. Next time we will learn how to program "Arcade Drive".
	}
}
