#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Hello! Today we are going to learn about variables.
//First, lets make a function called "forward".
//To declare a function, you need to put a "void" before the function name.

void forward()//You can see we have parentheses after our variable name.
{//Here again, we have the curly braces. These again show the compiler what is part of the variable and what is not.
	//Inside the curly braces, we are going to have what we want the variable to do.
	//In this variable, we want our motors to run forward at full speed.
	motor[leftDrive] = 127;//Again, we need the semicolin to show the compiler that the line is over.
	motor[rightDrive] = 127;
	//Ok! We have set both sides of the drive to full speed.
}
//Lets make another function now to tell the motors to stop.
void wheelsStop()
{
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;
}
//This function sets both wheels to zero.
//Now lets use these new functions in our program!

task main()
{
	//To use them, all we need to do is write the function name followed with the pair of parentheses.
	forward();//This sets the wheels to full speed.
	//To have them on for any significant amount of time, we need a wait command.
	wait1Msec(2000);//This will hold the program here for two seconds before letting it go on the the next line.
	wheelsStop();//Now we turn both wheels off. Done!
}
