#pragma config(Motor,  port1,           leftDrive,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          rightDrive,    tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This is an introduction to coding. In this course, you will learn how to create an autonomous program.

task main()//task main is the default loop that appears when you create a new file. This is where all of your code will go.
{//Curly Braces!!! Curly braces are used to show what is part of one loop and what is part of another. You always need matching sets for almost everything.
	//Here you can see that the type is indented. This is to help show what is part of each loop
	//First to make an autonomous routine, write motor[leftDrive] = 127.
	motor[leftDrive] = 127;//It should look like this.
	//Notice the semicolin after the 127, this tells the compiler that the line is over. If you forget it, the compiler will throw an error telling you.

	//Next, write the other motor in your drive. You need both to run at the same speed for the robot to move. It should look like this:
	motor[rightDrive] = 127;//But wait! The motor on the right side of the drive is not facing the same direction as the motor on the left! Why are we having them go the same direction?
	//Look back at the top of the screen, where we set up the motors. You can see that the rightDrive motor is reversed. This is why we have them go the same direction.

	//Good job! You made the motors spin in the same direction. However, they aren't going to stop. We need a "Wait" command to tell them how long to spin for.
	wait1Msec(2000);//This wait command will make the motor spin for 2 seconds, but it won't stop. We need to tell the motors to turn off.

	//To turn the motors off, you need to tell the motors to stop moving. This is shown by making the motors equal to zero.
	motor[leftDrive] = 0;
	motor[rightDrive] = 0;

	//There! We just turned the motors on for two seconds and make them turn off again!
}
